spring:
  h2: # http://localhost:8081/h2-console
    console:
      enabled: true
      settings:
        web-allow-others: true # for remote access    
  datasource:
    name: orders
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/appointment-db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # update, create, create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#  data:
#    rest:
#      base-path: /api